### PR TITLE
Added TRole : IdentityRole generic parameter to AddRavenDbIdentity.

### PR DESCRIPTION
**Pull request by JoshClose**
I needed to customize the `IdentityRole` object, so I added an overload that takes in `TRole` also.

### CODE REVIEW

**Comment by JudahGabriel** [comment]
I'll publish a new NuGet package with your changes. Thanks for contributing - you rock!

**Comment by JoshClose** [comment]
Awesome, thanks!

**Comment by JudahGabriel** [comment]
I've published a new package on NuGet with your changes. Thanks again!

**Comment by JudahGabriel** [comment]
p.s. I see you're in Minnesota. You coming to [Twin Cities Code Camp](https://twincitiescodecamp.com/)?

**Comment by JoshClose** [comment]
Thanks! Follow me back on Twitter and I'll PM you about Code Camp.

**Pull request merged**
